# Generated by Django 3.2.7 on 2021-09-11 20:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='identifier', unique=True)),
                ('identifier', models.CharField(default='', help_text='The name of this repository.', max_length=255)),
                ('url', models.CharField(blank=True, default='', help_text='An external URL for this location.', max_length=1023, verbose_name='URL')),
                ('location_description', models.CharField(blank=True, default='', help_text='A verbose description of the location.', max_length=255)),
                ('settlement', models.CharField(blank=True, default='', help_text='The name of a settlement such as a city, town, or village identified as a single geo-political or administrative unit.', max_length=255)),
                ('latitude', models.FloatField(blank=True, default=None, help_text='The latitude coordinate of this repository (in decimals).', null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(blank=True, default=None, help_text='The longitude coordinate of this repository (in decimals).', null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
            ],
            options={
                'ordering': ['identifier'],
            },
        ),
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='identifier', unique=True)),
                ('identifier', models.CharField(help_text='The identifier of the manuscript.', max_length=255)),
                ('alt_identifier', models.CharField(blank=True, default='', help_text='An alternative identifier of the manuscript.', max_length=255)),
                ('content_summary', models.CharField(blank=True, default='', help_text='A summary of the intellectual content in this manuscript. More details can be added below.', max_length=1023)),
                ('repository', models.ForeignKey(blank=True, default=None, help_text='The repository where this manuscript is held.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='kutub.repository')),
            ],
            options={
                'ordering': ['repository', 'identifier'],
            },
        ),
    ]
