# Generated by Django 3.2.7 on 2021-09-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='The measurement of the manuscript in millimetres along the axis parallel to its bottom, e.g. perpendicular to the spine of a book or codex.', null=True),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='The measurement in millimetres along the axis at a right angle to the bottom of the manuscript.', null=True),
        ),
    ]
