# Generated by Django 3.2.7 on 2021-09-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0002_auto_20210912_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='dimensions_description',
            field=models.CharField(blank=True, default='', help_text='A description of the dimensions of the leaves which can be used if the basic height and width values are not sufficient.', max_length=255),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='The measurement of the manuscript leaves in millimetres along the axis parallel to its bottom, e.g. perpendicular to the spine of a book or codex.', null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='The measurement in millimetres leaves along the axis at a right angle to the bottom of the manuscript.', null=True),
        ),
    ]
