# Generated by Django 3.2.7 on 2021-09-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0003_auto_20210912_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='extent_description',
            field=models.CharField(blank=True, default='', help_text='A description of the number of leaves in the manuscript.', max_length=255),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='extent_numeric',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='The number of leaves in the manuscript as an integer.', null=True),
        ),
    ]
