# Generated by Django 3.2.7 on 2021-09-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0004_auto_20210912_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='collation',
            field=models.CharField(blank=True, default='', help_text='A description of the arrangement of the leaves and quires of the manuscript.', max_length=255),
        ),
    ]
