# Generated by Django 3.2.7 on 2021-09-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0005_manuscript_collation'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='foliation',
            field=models.CharField(blank=True, default='', help_text='The scheme, medium or location of folio, page, column, or line numbers written in the manuscript, frequently including a statement about when and, if known, by whom, the numbering was done.', max_length=255),
        ),
    ]
