# Generated by Django 3.2.7 on 2021-09-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0006_manuscript_foliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='condition',
            field=models.CharField(blank=True, default='', help_text='A summary of the overall physical state of a manuscript, in particular where such information is not recorded elsewhere in the description.', max_length=255),
        ),
    ]
