# Generated by Django 3.2.7 on 2021-09-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0007_manuscript_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='collation',
            field=models.CharField(blank=True, default='', help_text='A description of the arrangement of the leaves and quires of the manuscript.', max_length=1023),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='condition',
            field=models.CharField(blank=True, default='', help_text='A summary of the overall physical state of a manuscript, in particular where such information is not recorded elsewhere in the description.', max_length=1023),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='dimensions_description',
            field=models.CharField(blank=True, default='', help_text='A description of the dimensions of the leaves which can be used if the basic height and width values are not sufficient.', max_length=1023),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='extent_description',
            field=models.CharField(blank=True, default='', help_text='A description of the number of leaves in the manuscript.', max_length=1023),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='foliation',
            field=models.CharField(blank=True, default='', help_text='The scheme, medium or location of folio, page, column, or line numbers written in the manuscript, frequently including a statement about when and, if known, by whom, the numbering was done.', max_length=1023),
        ),
    ]
