# Generated by Django 3.2.7 on 2021-09-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0008_auto_20210912_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='catchwords',
            field=models.CharField(blank=True, default='', help_text='The system used to ensure correct ordering of the quires or similar making up a manuscript, typically by means of annotations at the foot of the page.', max_length=1023),
        ),
    ]
