# Generated by Django 3.2.7 on 2021-09-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0009_manuscript_catchwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='signatures',
            field=models.CharField(blank=True, default='', help_text='A description of the leaf or quire signatures found within a codex.', max_length=1023),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='catchwords',
            field=models.CharField(blank=True, default='', help_text='The system used to ensure correct ordering of the quires or similar making up a codex, typically by means of annotations at the foot of the page.', max_length=1023),
        ),
    ]
