# Generated by Django 3.2.7 on 2021-09-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0010_auto_20210912_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='layout',
            field=models.CharField(blank=True, default='', help_text='How how text is laid out on the page or surface of the manuscript, including information about any ruling, pricking, or other evidence of page-preparation techniques.', max_length=1023),
        ),
    ]
