# Generated by Django 3.2.7 on 2021-09-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0011_manuscript_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='decoration_description',
            field=models.CharField(blank=True, default='', help_text='A description of the decoration of the manuscript.', max_length=1023),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='hand_description',
            field=models.CharField(blank=True, default='', help_text='A description of all the different hands used in the manuscript.', max_length=1023),
        ),
    ]
