# Generated by Django 3.2.7 on 2021-09-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0012_auto_20210912_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='music_notation',
            field=models.CharField(blank=True, default='', help_text='A description of the type of musical notation.', max_length=1023),
        ),
    ]
