# Generated by Django 3.2.7 on 2021-09-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0013_manuscript_music_notation'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='binding_description',
            field=models.CharField(blank=True, default='', help_text='A description of the state of the present and former bindings of a manuscript, including information about its material, any distinctive marks, and provenance information.', max_length=1023),
        ),
    ]
