# Generated by Django 3.2.7 on 2021-09-12 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0014_manuscript_binding_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='seal_description',
            field=models.CharField(blank=True, default='', help_text='information about the seal(s) attached to documents to guarantee their integrity, or to show authentication of the issuer or consent of the participants.', max_length=1023),
        ),
    ]
