# Generated by Django 3.2.7 on 2021-09-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0015_manuscript_seal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='support_description',
            field=models.CharField(blank=True, default='', help_text='A description of the physical support for the written part of a manuscript.', max_length=1023),
        ),
    ]
