# Generated by Django 3.2.7 on 2021-09-14 08:21

from django.db import migrations
import kutub.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0021_auto_20210914_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='acquisition',
            field=kutub.fields.DescriptionField(blank=True, default='', help_text='Any descriptive or other information concerning the process by which the manuscript entered the holding institution.'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='provenance',
            field=kutub.fields.DescriptionField(blank=True, default='', help_text='Any description or other information concerning a single identifiable episode during the history of a manuscript, manuscript part, or other object after its creation but before its acquisition. Separated by one or more line breaks.'),
        ),
    ]
