# Generated by Django 3.2.7 on 2021-09-16 00:39

import django.core.validators
from django.db import migrations
import kutub.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0026_auto_20210915_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='summary',
            field=kutub.fields.DescriptionField(blank=True, default='', help_text='A summary of the content of this item.', validators=[django.core.validators.RegexValidator('^[ -\ud7ff\t\n\r\ue000-�𐀀-\U0010ffff]*$', 'Only valid XML characters allowed.')]),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='source',
            field=kutub.fields.DescriptionField(blank=True, default='', help_text='Describes the original source for the information contained with this manuscript description.', validators=[django.core.validators.RegexValidator('^[ -\ud7ff\t\n\r\ue000-�𐀀-\U0010ffff]*$', 'Only valid XML characters allowed.')]),
        ),
    ]
