# Generated by Django 3.2.7 on 2021-09-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0027_auto_20210916_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='end_folio',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='The folio number where this content item ends.', null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='end_folio_side',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('r', 'Recto'), ('v', 'Verso')], default='', help_text='The folio side (i.e. recto or verso) where this content item ends.', max_length=1),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='start_folio',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='The folio number where this content item begins.', null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='start_folio_side',
            field=models.CharField(blank=True, choices=[('', 'Unknown'), ('r', 'Recto'), ('v', 'Verso')], default='', help_text='The folio side (i.e. recto or verso) where this content item begins.', max_length=1),
        ),
    ]
