# Generated by Django 3.2.7 on 2021-10-01 03:20

import django.core.validators
from django.db import migrations
import kutub.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0028_auto_20210916_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='note',
            field=kutub.fields.DescriptionField(blank=True, default='', help_text='A general description of the manuscript if the content cannot be easily placed in the other fields.', validators=[django.core.validators.RegexValidator('^[ -\ud7ff\t\n\r\ue000-�𐀀-\U0010ffff]*$', 'Only valid XML characters allowed.')]),
        ),
    ]
