# Generated by Django 3.2.7 on 2021-10-01 06:05

import django.core.validators
from django.db import migrations
import kutub.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0029_manuscript_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='iiif_manifest_url',
            field=kutub.fields.DescriptionField(blank=True, default='', help_text='A URL to a IIIF manifest with facsimiles of this manuscript.', validators=[django.core.validators.RegexValidator('^[ -\ud7ff\t\n\r\ue000-�𐀀-\U0010ffff]*$', 'Only valid XML characters allowed.')]),
        ),
    ]
