# Generated by Django 3.2.7 on 2021-10-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0031_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='region_tag',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='script_tag',
            new_name='script',
        ),
    ]
