# Generated by Django 3.2.7 on 2021-10-01 20:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import kutub.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0032_auto_20211001_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='main_language',
            field=models.ForeignKey(blank=True, default=None, help_text='The main language used in this content item.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='main_language_item_set', to='kutub.language'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='other_languages',
            field=models.ManyToManyField(help_text='Other languages used in this content item.', related_name='other_language_item_set', to='kutub.Language'),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='text_language_description',
            field=kutub.fields.DescriptionField(blank=True, default='', help_text='A description of the language(s).', validators=[django.core.validators.RegexValidator('^[ -\ud7ff\t\n\r\ue000-�𐀀-\U0010ffff]*$', 'Only valid XML characters allowed.')]),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='main_language',
            field=models.ForeignKey(blank=True, default=None, help_text='The main language used.', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='main_language_set', to='kutub.language'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='other_languages',
            field=models.ManyToManyField(help_text='Other languages used.', related_name='other_language_set', to='kutub.Language'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='text_language_description',
            field=kutub.fields.DescriptionField(blank=True, default='', help_text='A description of the language(s).', validators=[django.core.validators.RegexValidator('^[ -\ud7ff\t\n\r\ue000-�𐀀-\U0010ffff]*$', 'Only valid XML characters allowed.')]),
        ),
    ]
