# Generated by Django 3.2.7 on 2021-10-01 21:52

import django.core.validators
from django.db import migrations
import kutub.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0033_auto_20211001_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='url',
            field=kutub.fields.DescriptionField(blank=True, default='', help_text='An external URL for this manuscript.', validators=[django.core.validators.RegexValidator('^[ -\ud7ff\t\n\r\ue000-�𐀀-\U0010ffff]*$', 'Only valid XML characters allowed.')], verbose_name='URL'),
        ),
    ]
