# Generated by Django 5.1.5 on 2025-04-04 00:41

import django.core.validators
import kutub.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0038_alter_language_extlang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='physical_description_summary',
            field=kutub.fields.DescriptionField(blank=True, default='', help_text='A summary of the physical description of the manuscript.', validators=[django.core.validators.RegexValidator('^[ -\ud7ff\t\n\r\ue000-�𐀀-\U0010ffff]*$', 'Only valid XML characters allowed.')]),
        ),
    ]
