# Generated by Django 5.1.5 on 2025-04-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0039_manuscript_physical_description_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='The order in which this manuscript should be displayed.'),
        ),
    ]
