# Generated by Django 5.1.5 on 2025-04-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kutub', '0040_manuscript_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='The order in which this manuscript should be displayed.', null=True),
        ),
    ]
